# Generated by Django 3.2.16 on 2023-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='areas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
