# Generated by Django 3.2.16 on 2023-02-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, verbose_name='')),
                ('descripcion', models.CharField(max_length=200, verbose_name='')),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='')),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('UNITARIO', 'UNITARIO'), ('PROMEDIADO', 'PROMEDIADO')], max_length=30, verbose_name='Tipo de Insumo')),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('razonSocial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razon social')),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Clínica externa', 'Clínica externa'), ('Odontos', 'Odontos')], max_length=30, verbose_name='Tipo de Sucursal')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Nombre de Dr.')),
                ('nombreClinica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de clinica')),
                ('razonSocial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razon social')),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('metodologiaTrabajo', models.CharField(choices=[('DIENTES', 'DIENTES'), ('MAXILAR', 'MAXILAR'), ('MIXTO', 'MIXTO')], max_length=30, verbose_name='Metodologia de Trabajo')),
                ('precio', models.IntegerField()),
                ('duracionEstimadaOdontos', models.IntegerField(verbose_name='Duracion estiamada Odontos hasta 4 dientes')),
                ('duracionEstimadaParticulares', models.IntegerField(verbose_name='Duracion estimada particulares hasta 4 dientes')),
                ('duracionEstimadaOdontos5', models.IntegerField(verbose_name='Duracion estiamada Odontos 5 o mas dientes')),
                ('duracionEstimadaParticulares5', models.IntegerField(verbose_name='Duracion estimada particulares 5 o mas dientes')),
                ('minimoDientes', models.IntegerField(verbose_name='Minimo de Dientes')),
                ('maximoDientes', models.IntegerField(verbose_name='Maximo de Dientes')),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreApellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
