# Generated by Django 3.2.16 on 2023-02-17 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trabajoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumo', verbose_name=''),
        ),
        migrations.AddField(
            model_name='trabajoinsumo',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipotrabajo'),
        ),
        migrations.AddField(
            model_name='tipotrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttrabajo_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipotrabajo',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidad'),
        ),
        migrations.AddField(
            model_name='tipotrabajo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttrabajo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarea_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursal_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursal_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vendedor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ciudad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcacolor',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mcolor_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marcacolor',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mcolor_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumo_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fasetarea',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ftarea_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fasetarea',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.faseespecialidad'),
        ),
        migrations.AddField(
            model_name='fasetarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tarea', verbose_name=''),
        ),
        migrations.AddField(
            model_name='faseespecialidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fase_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faseespecialidad',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidad'),
        ),
        migrations.AddField(
            model_name='faseespecialidad',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name=''),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidad_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidad_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colordetalle',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colordetalle',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marcacolor'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
