# Generated by Django 3.2.16 on 2023-04-24 02:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrdenAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='')),
                ('area', models.CharField(choices=[('CAD CAM', 'CAD CAM'), ('METAL', 'METAL'), ('METALOCERAMICA', 'METALOCERAMICA'), ('CEROMERO', 'CEROMERO'), ('ACRILICO', 'ACRILICO'), ('PLACAS', 'PLACAS'), ('MAQUILLAJE', 'MAQUILLAJE')], max_length=100, verbose_name='')),
                ('tipoTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotrabajo')),
            ],
            options={
                'unique_together': {('tipoTrabajo', 'orden')},
            },
        ),
    ]
