# Generated by Django 3.2.16 on 2023-08-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipoordenareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombreClinica',
            field=models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre de clinica'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(choices=[('Clinica externa', 'Clinica externa'), ('Odontos', 'Odontos')], max_length=30, verbose_name='Tipo de Sucursal'),
        ),
    ]
