# Generated by Django 3.2.16 on 2023-02-17 01:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenTrabajo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('observacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('estado', models.CharField(blank=True, default='COURIER ENTRANTE', max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
                ('envioCourrier', models.BooleanField(default=False, verbose_name='Envio Courrier')),
                ('metodoEnvio', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Modificación', 'Modificación'), ('Repetición', 'Repetición')], default='Ninguno', max_length=50, verbose_name='Método de reenvío de trabajo')),
                ('trabajoRepetido', models.IntegerField(blank=True, null=True, verbose_name='Nº trabajo a repetir')),
                ('motivoModificacion', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Motivo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical orden trabajo',
                'verbose_name_plural': 'historical orden trabajos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MetodoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.BooleanField(default=False, verbose_name='Trabajo Express')),
                ('dientes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=5000, null=True)),
                ('maxilarSuperiorCompleto', models.BooleanField(default=False, verbose_name='Maxilar Superior Completo')),
                ('maxilarInferiorCompleto', models.BooleanField(default=False, verbose_name='Maxilar Inferior Completo')),
                ('fechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('modoEnvio', models.CharField(choices=[('Modelo', 'Modelo'), ('Escaneado', 'Escaneado'), ('Impreso', 'Impreso')], default='Modelo', max_length=50, verbose_name='Se envía')),
                ('observacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(blank=True, max_length=500, null=True)),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
                ('observacionTecnico', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observacion')),
                ('factura', models.CharField(blank=True, max_length=30, null=True)),
                ('facturaDocumento', models.FileField(blank=True, null=True, upload_to='facturas/', verbose_name='Fichero')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesTrabajoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, max_length=500, null=True)),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo', models.CharField(blank=True, max_length=5000, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rechazos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='orden/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('observacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('estado', models.CharField(blank=True, default='COURIER ENTRANTE', max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(blank=True, null=True)),
                ('modificado_el', models.DateTimeField(blank=True, null=True)),
                ('envioCourrier', models.BooleanField(default=False, verbose_name='Envio Courrier')),
                ('metodoEnvio', models.CharField(choices=[('Ninguno', 'Ninguno'), ('Modificación', 'Modificación'), ('Repetición', 'Repetición')], default='Ninguno', max_length=50, verbose_name='Método de reenvío de trabajo')),
                ('trabajoRepetido', models.IntegerField(blank=True, null=True, verbose_name='Nº trabajo a repetir')),
                ('motivoModificacion', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Motivo')),
                ('clinicaExterna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Clínica Externa')),
            ],
        ),
    ]
