# Generated by Django 3.2.16 on 2023-02-17 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor'),
        ),
        migrations.AddField(
            model_name='ordenfoto',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='ordenestrabajoestado',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='ordenestrabajoestado',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenes.ordendetalle'),
        ),
        migrations.AddField(
            model_name='ordenestrabajoestado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.colordetalle'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordentrabajo_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordentrabajo_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='modoRetiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordenes.metodoretiro'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipotrabajo'),
        ),
        migrations.AddField(
            model_name='metodoretiro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metodoRetiro_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metodoretiro',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metodoRetiro_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='clinicaExterna',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sucursal', verbose_name='Clínica Externa'),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paciente'),
        ),
        migrations.AddField(
            model_name='historicalordentrabajo',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.vendedor'),
        ),
    ]
