# Generated by Django 3.2.16 on 2023-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetalle',
            name='etapaActual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etapa actual'),
        ),
        migrations.AddField(
            model_name='ordendetalle',
            name='etapaOrden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
